### ISSUE TITLE
BUG Input event triggered when value prop is changed

### ISSUE THREAD

**Issue by Soviut** [dm4t2/vue-currency-input#89]
I'm using the vue-currency-input in an app that uses Vuex. As such, I'm not using the v-model, I'm using a bound `:value` field to get Vuex state into the component and `@input` event to get updated values back out.

I have several currency fields and noticed they're all triggering their `@input` events when their `:value` changes, rather than just when someone inputs something in the field. This causes a cascade of fields to change.

I would expect that the `@input` only triggers when a human causes the input, the way regular form fields work.

I'll gladly try my hand at a PR if you agree.

**Comment by dm4t2** [comment]
Hi, which version do you use? This was originally fixed in [1.15.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.15.1).

**Comment by alipishevar** [comment]
> I'm using the vue-currency-input in an app that uses Vuex. As such, I'm not using the v-model, I'm using a bound `:value` field to get Vuex state into the component and `@input` event to get updated values back out.
> 
> I have several currency fields and noticed they're all triggering their `@input` events when their `:value` changes, rather than just when someone inputs something in the field. This causes a cascade of fields to change.
> 
> I would expect that the `@input` only triggers when a human causes the input, the way regular form fields work.
> 
> I'll gladly try my hand at a PR if you agree.



> Hi, which version do you use? This was originally fixed in [1.15.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.15.1).



version is updated...
I have the same problem

**Comment by Soviut** [comment]
I believe I was using the most recent version

**Comment by dm4t2** [comment]
@Soviut: I can not reproduce this: 
https://codesandbox.io/s/elated-sky-th2uz

If I change the state directly with Vue DevTools there's only a `change` triggered, rather than an `input` event. Please provide more information to reproduce. Feel free to fork my CodeSandbox.

**Comment by alipishevar** [comment]
edited 
https://codesandbox.io/s/stoic-banach-64huj

**Comment by alipishevar** [comment]
new edit 
https://codesandbox.io/s/aged-flower-pm2ef

**Comment by DevelGitH** [comment]
@dm4t2 I've the same problem. On my example you can open the devtools and you will see that the message is logged before actually a change happened.
With version 1.15.1 the problem was solved.

https://codesandbox.io/s/upbeat-mountain-4mdek

**Comment by dm4t2** [comment]
@alipishevar I noticed in your example that the distraction free formatting gets lost each time the component's context changes. Is that your issue?

@DevelGitH So everything's fine or is there still an issue?

**Comment by DevelGitH** [comment]
@dm4t2 only for the version 1.15.1
Would be glad if the bug will be resolved also for the newest version. In the meantime I've to use the old one or I will run into some conflicts with some other events.

**Comment by alipishevar** [comment]
> @alipishevar I noticed in your example that the distraction free formatting gets lost each time the component's context changes. Is that your issue?
> 
Yes of course

**Comment by Soviut** [comment]
I was no using the distraction-free mode in mine, it was updating commas as you typed.

@dm4t2 I'll have to try again and see about using the difference between `input` and `change` events.

**Comment by dm4t2** [comment]
The event handling issues should be fixed with [Release 1.17.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.0) 🎉

**Comment by DevelGitH** [comment]
> The event handling issues should be fixed with [Release 1.17.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.0) 🎉

Did you removed the events completely? The events on the component aren't working anymore. See my new [issue](https://github.com/dm4t2/vue-currency-input/issues/91)

**Comment by dm4t2** [comment]
Unfortunately there was a bug not covered/detectable by the unit tests. Change events should be triggered correctly again with [Release 1.17.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.17.1).
